### ISSUE TITLE
Error starting userland proxy: listen tcp 0.0.0.0:3306: bind: address already in use

### ISSUE THREAD

**Issue by mappedinn** [FlyersWeb/angular-symfony#22]
Hi,

First of all, thank you for sharing this very interesting example on angular and symfony.

I am actually trying to run this example on my machine (Ubuntu 16.04) on which I have LAMP up and running. Here, it is normal the port 3306 is being used by MySQL as shown by the command below:

```sh
$ netstat -pna | grep 3306
#(Not all processes could be identified, non-owned process info
# will not be shown, you would have to be root to see it all.)
#tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      - 
```

The error I am getting after typing `$ docker-compose up -d` is:

**Starting dockerify_db_1
ERROR: driver failed programming external connectivity on endpoint dockerify_db_1 (aa5ef99767df6a36c59ff036e1386d41e504970dadb79bb9a326f86f8a1d47d2): Error starting userland proxy: listen tcp 0.0.0.0:3306: bind: address already in use**

If I am well understanding the error, it is saying that there more than one application is using the port 
3306 which is absolutely true. I tried to fix that by changing the ports in the [line 22] (https://github.com/FlyersWeb/angular-symfony/blob/master/dockerify/docker-compose.yml#L22) as follows `3307:3307`

To solve the issue, I did the following:
* I deleted all the containers in my machine `$ docker rm $(docker ps -a -q)`
* I rebuilt the image by this command `$ docker-compose build` 

**but** I still do have the same error !!!

Any idea to fix the issue?

---
```sh
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 22:01:48 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 22:01:48 2016
 OS/Arch:      linux/amd64

```

**Comment by mappedinn** [comment]
the change did not work because I was doing it on another copy of the project. Consequently, rebuilding the images did not solve the problem.

Anyway, now it is up and running by changing the docker-compose.yml as follows:

```yml
application:
    build: ../back-end
    volumes:
        - ../back-end:/var/www
        - ../back-end/web:/var/www/html
        - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
        - ./php-fpm/timezone.ini:/usr/local/etc/php/conf.d/timezone.ini
        - ./php-fpm/symfony.pool.conf:/etc/php5/fpm/pool.d/symfony.pool.conf
    links:
        - db

client:
    build: ../front-end
    volumes:
      - ../front-end:/var/www
    links:
      - nginx-back

db:
    image: mysql
    ports:
        - 3307:3306
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: symfony

nginx-front:
    image: nginx
    ports:
        - 8080:80
    links:
        - client
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/express.conf:/etc/nginx/conf.d/default.conf

nginx-back:
    image: nginx
    ports:
        - 81:8080
    links:
        - application
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/symfony.conf:/etc/nginx/conf.d/default.conf
```

One more change (just for the case of) was done on php.ini at [line 1090](https://github.com/FlyersWeb/angular-symfony/blob/master/dockerify/php-fpm/php.ini#L1090)

```ini
mysql.default_port = 3307
```

Hope it will help others :)
